import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub, AiFillLinkedin} from 'react-icons/ai';
import Image from 'next/image';
import hackathon from '../public/hackathon.png';
import Robbie from '../public/Robbie-1.JPG';
import movie from '../public/movie_review.png';
import instagram from '../public/instagram-1.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Robbie Huang Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/*Navbar*/}
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          {/*padding, margin-bottom, flex, justify*/}
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>DevelopedbyRob</h1>
            <ul className='flex itmes-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Robbie Huang</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Developer</h3>
            <p className='text-medium py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>
              Computer Science student at Queen's University in 3rd year.
              Enjoys machine learning and web developement!
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='https://github.com/RobbieHuang2002'>
              <AiFillGithub />
            </a>
            <a href='https://www.linkedin.com/in/robbie-huang-8179601b6/'>
              <AiFillLinkedin />
            </a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={Robbie} layout='fill' objectFit='cover'/>
          </div>
        </section>
        
        <section>
          <div className='text-center'>
            {/*projects title */}
            <h3 className='text-3xl py-1'>Projects I've built</h3>
            <p className='text-md py-2 leading-8 text-gray-80'>
              Since the beggining of my journey as a developer, I've built different apps! 
            </p>
          </div>
          {/*project cards*/}
          <div className='lg:flex justify-center gap-10'>
            {/*first project card */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={hackathon} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Chef Buddy</h3>
              <p className='py-2 max-w-xs'>
                Snap a photo of your fridge and see what you can make
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>google-vision api</p>
              <p className='text-gray-800 py-1'>firebase</p>
              <p className='text-gray-800 py-1'>javascript</p>
              <a href='https://devpost.com/software/chefbuddy' className='inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-teal-600 rounded-lg hover:bg-teal-800'>
                Read More
              </a>
            </div>
            {/*second project card */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={movie} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Movie Review NLP </h3>
              <p className='py-2 max-w-xs'>
                determining between positive and negative movie reviews using sklearn
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Python</p>
              <p className='text-gray-800 py-1'>sklearn library</p>
              <p className='text-gray-800 py-1'>pandas data cleaning</p>
              <a href="https://github.com/RobbieHuang2002/movie-review-nlp" className='inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-teal-600 rounded-lg hover:bg-teal-800'>
                Read More
              </a>
            </div>
            {/*third project card*/}
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={instagram} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'></h3>
              <p className='py-2'>
                creating elegant deisng suited for your needs 
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>photoshop</p>
              <p className='text-gray-800 py-1'>figma</p>
              <p className='text-gray-800 py-1'>illustrator</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
